
import {
    collection,
    onSnapshot,
    query,
    getDocs,
    doc,
    getDoc,
    updateDoc,
    setDoc,
    orderBy,
    Timestamp,
    runTransaction,
    where,
    addDoc,
    arrayUnion,
    FieldValue,
} from "firebase/firestore";

import { db } from "@/config/firebase.config.js";

export async function addNewArticle(
    articleId,
    article
) {
    const articleToStore = {
        article_id: articleId,
        title: article.title,
        link: article.link,
        creator: article.creator,
        image_url: article.image_url,
        description: article.description,
        content: article.content,
        pubDate: (new Date(article.pubDate)).getTime(),
        source_id: article.source_id,
        category: article.category,
        dateStored: (new Date()).getTime(),
    }

    // Add article to database
    await setDoc(doc(db, "articles", articleId), articleToStore);
}

// Returns a list of article id strings
export async function getArticleIdList() {
    const q = query(collection(db, "articles"));
    const results = await getDocs(q);

    return results.docs.map(currDoc => {
        return currDoc.id;
    });
}

// Get an article object
export async function getArticle(articleId) {
    const docRef = doc(db, "articles", articleId);
    const docSnap = await getDoc(docRef);

    if (docSnap.exists()) {
        return docSnap.data();
    } else {
        return null;
    }
}

// Add articleID to the chats array in the users document
export async function addArticleIdToUser(userId, articleId) {
    const userRef = doc(db, "users", userId);

    await updateDoc(userRef, {
        chats: arrayUnion(articleId)
    });
    // chatId = userId + articleId << In this way all chats still have unique Ids
}

// Update user's article history and category history
export async function updateUserHistory(userId, articleId) {
    const userRef = doc(db, "users", userId);
    const category = (await getArticle(articleId)).category[0];
    const user_category_count = (await getDoc(userRef)).data()["category_history"];
    // Check if user has category_history, if not, create one
    if (!user_category_count) {
        await updateDoc(userRef, {
            article_history: arrayUnion(articleId),
            category_history: {
                [category]: 1
            }
        });
        return;
    }
    // Else, update the category_history
    if (!user_category_count[category]) {
        await updateDoc(userRef, {
            chats: arrayUnion(articleId),
            article_history: arrayUnion(articleId),
            // Add new category to user's category_history
            category_history: {
                ...user_category_count,
                [category]: 1
            }
        });
        return;
    }
    await updateDoc(userRef, {
        chats: arrayUnion(articleId),
        article_history: arrayUnion(articleId),
        category_history: {
            ...user_category_count,
            [category]: user_category_count[category] + 1
        }
    });
}

// Add user to user collection with empty chat list
export async function addUserIfNotExist(userId) {
    console.log("ADDING USER");
    const userRef = doc(db, "users", userId);

    const docSnap = await getDoc(userRef);

    if (!docSnap.exists()) {
        await setDoc(userRef, {
            chats: []
        });
    }
}

// Add messageID to the messages array in the chats document
export async function addMessageIdToChat(chatId, messageId) {
    const chatRef = doc(db, "chats", chatId);

    await updateDoc(chatRef, {
        messages: arrayUnion(messageId)
    });
}

// Add message to the messages collection with id generated by firebase and return the id
export async function addMessage(message, chatId) {
    const messageRef = await addDoc(collection(db, "messages"), message);

    // Add message id to the chat
    await addMessageIdToChat(chatId, messageRef.id);

    return messageRef.id;
}

// Add chat
export async function addChat(chatToStore, articleId, newChatId, userId) {
    const chatRef = doc(db, "chats", newChatId);

    const docSnap = await getDoc(chatRef);

    if (!docSnap.exists()) {
        // Add chat id to the user
        await addArticleIdToUser(userId, articleId);


        await setDoc(doc(db, "chats", newChatId), chatToStore);
    }
}

// Get a chat object
export async function getChat(chatId) {
    const docRef = doc(db, "chats", chatId);
    const docSnap = await getDoc(docRef);

    if (docSnap.exists()) {
        return docSnap.data();
    } else {
        return null;
    }
}

// Get a message object
export async function getMessage(messageId) {
    const docRef = doc(db, "messages", messageId);
    const docSnap = await getDoc(docRef);

    if (docSnap.exists()) {
        return docSnap.data();
    } else {
        return null;
    }
}

// CAUTION: This returns a list of article IDs. To get the chat ID u have to do userId + articleId
export async function getChatIdList(userId) {
    const docRef = doc(db, "users", userId);
    const docSnap = await getDoc(docRef);

    if (Array.isArray(docSnap.data().chats)) {
        return docSnap.data().chats.map(currChat => {
            return currChat
        });
    } else {
        return [];
    }
}

// Get message list for chatID
export async function getMessageList(chatId) {
    const docRef = doc(db, "chats", chatId);
    const docSnap = await getDoc(docRef);

    if (docSnap.exists()) {
        return docSnap.data().messages;
    } else {
        return [];
    }
}